backend/controllers/ClassifiedController.php
<?php

namespace backend\controllers;

use common\models\User;
use common\models\Users;
use Yii;
use common\models\ClassifiedListings;
use backend\models\ClassifiedSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\AdminController;

/**
 * ClassifiedController implements the CRUD actions for ClassifiedListings model.
 */
class ClassifiedController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'view', 'delete', 'users-list', 'users-list-ajax', 'upload'],
                'rules' => [
                    // allow authenticated users
                        [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->identity->user_type != \common\models\Users::ROLE_ADMIN) {
                                return $this->redirect('/login');
                            }else if(Yii::$app->user->identity->user_type == \common\models\Users::ROLE_ADMIN){
                                return true;
                            }
                        }
                    ],
                // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all ClassifiedListings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ClassifiedListings model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->redirect(Yii::$app->request->referrer);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ClassifiedListings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClassifiedListings();
        
        $post = Yii::$app->request->post();
        
        if(isset(Yii::$app->request->isPost) && !empty(Yii::$app->request->post())){
            $post['ClassifiedListings']['start_date'] = time();
            $post['ClassifiedListings']['date_added'] = time();
            $dur = (isset($post['ClassifiedListings']['duration']) && !empty($post['ClassifiedListings']['duration'])) ? $post['ClassifiedListings']['duration'] : $post['ClassifiedListings']['start_date'];
            $post['ClassifiedListings']['end_date'] = time() + ($dur * 24 * 60 * 60);
        }
        
        if ($model->load($post) && $model->save()) {
            Yii::$app->session->setFlash('success', "Record Successfully Create");
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ClassifiedListings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Record Successfully Updated");
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ClassifiedListings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)   
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ClassifiedListings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClassifiedListings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClassifiedListings::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionUsersList($user_type)
    {
        $accounts = Users::find()->select(['id', 'contact_name', 'company_name'])->where(['user_type' => $user_type, 'status' => Users::STATUS_ACTIVE])->limit(300)->all();
        if (!empty($accounts)){
            echo '<option> Select Account </option>';
            foreach ($accounts as $account){
                if ($user_type == Users::ROLE_BUSINESS){
                    echo '<option value="'.$account->id.'">'.$account->company_name.'</option>';
                } else {
                    echo '<option value="'.$account->id.'">'.$account->contact_name.'</option>';
                }
            }
        } else {
            echo '<option value=" "> - </option>';
        }
        exit;
    }
    
    public function actionUsersListAjax($q = null, $id = null, $ad_type = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $userList = Users::find()->select(['id', 'contact_name as text'])
                                        ->where(['like', 'username' , $q])
                                        ->orWhere(['like', 'contact_name' , $q])
                                        ->orWhere(['like', 'company_name' , $q])
                                        ->andWhere(['user_type' => $ad_type])
                                        ->andWhere(['status' => Users::STATUS_ACTIVE])
                                        ->limit(100)
                                        ->asArray()
                                        ->all();
            $out['results'] = $userList;
        }
            
        return $out;
        
    }

    public function actionUpload()
    {
        $fileName = 'file';
        $uploadPath = 'uploads';

        if (isset($_FILES[$fileName])) {
            $file = \yii\web\UploadedFile::getInstanceByName($fileName);

            if ($file->saveAs($uploadPath . '/' . $file->name)) {
                //Now save file data to database

                echo \yii\helpers\Json::encode($file);
            }
        } else {
            return $this->render('upload');
        }

        return false;
    }
}

frontend/controllers/ClassifiedController.php
<?php

namespace frontend\controllers;

use common\models\Users;
use Yii;
use common\models\ClassifiedListings;
use common\models\ClassifiedCategories;
use frontend\models\ClassifiedSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\AdsenseCategory;
use backend\models\CarModels;

/**
 * ClassifiedController implements the CRUD actions for ClassifiedListings model.
 */
class ClassifiedController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                 'denyCallback' => function ($rule, $action) {
                    Yii::$app->session->setFlash('error', 'Please login to continue');
                    return $this->redirect('/login');
                },
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'search', 'view','search-car'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'search', 'view', 'create', 'update','delete','child-cats','search-car', 'model-list'],
                        'roles' => ['@'],
                    ],
                // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all ClassifiedListings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->recentAds(Yii::$app->request->queryParams);
        $adsence = AdsenseCategory::find()->where(['ad_location' => 'Home Page'])->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'adsence'=> $adsence,
        ]);
    }
    
    /**
     * Lists all ClassifiedListings models.
     * @return mixed
     */
    public function actionSearch()
    {
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $params = Yii::$app->request->queryParams;
        if(isset($params['per-page'])){
            $dataProvider->pagination = ['pageSize' => $params['per-page'],];
        } else {
            $dataProvider->pagination = ['pageSize' => 15,];
        }
        
        $categories = ClassifiedCategories::find()->where(['parent_id' => 0])->andWhere(['status' => 'active'])->all();
        $ifExist = [];
        
        if(isset($params['ClassifiedSearch']['slug'])){
            $ifExist = \common\models\ClassifiedCategories::find()->where(['slug' => $params['ClassifiedSearch']['slug']])->andWhere(['status' => 'active'])->one();
        }
        if(isset($ifExist->parent_id) && $ifExist->parent_id == 0){
            $subCategories = ClassifiedCategories::find()->where(['parent_id' => $ifExist->id])->andWhere(['status' => 'active'])->all();
        }else{
            $subCategories = ClassifiedCategories::find()->where(['!=', 'parent_id', 0])->andWhere(['status' => 'active'])->all();
        }
        
        $countries = \common\models\LocationsCounties::find()->where(['status' => \common\models\Users::STATUS_ACTIVE])->all();
//                $data = $dataProvider->query->all();
//        foreach ($data as $key => $value) {
//            echo "<pre>";
//            print_r($value);exit;
//        }
        
        return $this->render('ads-listing', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'categories' => $categories,
            'subCategories' => $subCategories,
            'countries' => $countries
        ]);
    }
    
    
    /**
     * Lists all ClassifiedListings models.
     * @return mixed
     */
    public function actionSearchCar()
    {
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
//        $max = $dataProvider->query->find()->max('price');
        
        $params = Yii::$app->request->queryParams;
        if(isset($params['per-page'])){
            $dataProvider->pagination = ['pageSize' => $params['per-page'],];
        } else {
            $dataProvider->pagination = ['pageSize' => 15,];
        }
        
        $categories = ClassifiedCategories::find()->where(['parent_id' => 0])->andWhere(['status' => 'active'])->all();
        $ifExist = [];
        
        if(isset($params['ClassifiedSearch']['slug'])){
            $ifExist = \common\models\ClassifiedCategories::find()->where(['slug' => $params['ClassifiedSearch']['slug']])->andWhere(['status' => 'active'])->one();
        }
        if(isset($ifExist->parent_id) && $ifExist->parent_id == 0){
            $subCategories = ClassifiedCategories::find()->where(['parent_id' => $ifExist->id])->andWhere(['status' => 'active'])->all();
        }else{
            $subCategories = ClassifiedCategories::find()->where(['!=', 'parent_id', 0])->andWhere(['status' => 'active'])->all();
        }
        
        $countries = \common\models\LocationsCounties::find()->where(['status' => \common\models\Users::STATUS_ACTIVE])->all();
        $carMakes = \backend\models\CarMakes::find()->where(['status' => \common\models\Users::STATUS_ACTIVE])->all();
        
        return $this->render('car-listing', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'categories' => $categories,
            'subCategories' => $subCategories,
            'countries' => $countries,
            'carMakes' => $carMakes
        ]);
    }

    /**
     * Displays a single ClassifiedListings model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView()
    {
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $params = Yii::$app->request->queryParams;
        if(isset($params['ClassifiedSearch']['id']) && !empty($params['ClassifiedSearch']['id'])){
            $model = ClassifiedListings::findOne(['id' => $params['ClassifiedSearch']['id']]);
            $model->views = $model->views + 1;
            $model->save(false);
        }
        
        return $this->render('view', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new ClassifiedListings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        
        if(Yii::$app->user->identity->user_type == Users::ADMIN_USER){
            $this->redirect('/admin/classified/create');
        }
        
        $largePath = './uploads/large';
        $smallPath = './uploads/small';
        $fileName = 'ClassifiedListings';

        if (isset($_FILES[$fileName]) && !empty($_FILES[$fileName])) {

            $imgCheck = \yii\web\UploadedFile::getInstancesByName($fileName);

            foreach ($imgCheck as $f => $file) {
                $size = getimagesize($file->tempName);
                if($size[0] < 768){
                    Yii::$app->session->setFlash('error', "Image size is less then 768px");
                    return $this->redirect(Yii::$app->request->referrer);
                }
            
            }

        }
        $price_type = ClassifiedListings::CLASSIFIED_ADVERT;
        $ads_price = \backend\models\base\Prices::find()->where(['price_type' => $price_type])->one();
        
       if(Yii::$app->user->identity->account_balance < $ads_price->price){
           Yii::$app->session->setFlash('error', "You don't have enough Balance to create add");
       }
        $model = new ClassifiedListings();
        
        $userMoldel = Users::findOne($userId = Yii::$app->user->identity->id);
        
        if(isset(Yii::$app->request->isPost) && $model->load(Yii::$app->request->post())){
           if(Yii::$app->user->identity->account_balance < $ads_price->price){
               Yii::$app->session->setFlash('error', "You don't have enough Balance to create add");
               return $this->redirect(Yii::$app->request->referrer);
           }else{
                $post = Yii::$app->request->post();
                $model->load(Yii::$app->request->post());
                $model->user_id = Yii::$app->user->identity->id;
                $model->start_date = time();
                $model->date_added = time();
                $model->end_date = time() + (120*24*60*60);
                $model->search_price = preg_replace("/[^0-9+.]/","",$post['ClassifiedListings']['price']);
                $model->search_options = empty($post['ClassifiedListings']['search_options']) ? "" : implode(',', $post['ClassifiedListings']['search_options']);

                if ($model->save()) {
                    
                    
                    
                    if (isset($_FILES[$fileName]) && !empty($_FILES[$fileName])) {
                        $files = \yii\web\UploadedFile::getInstancesByName($fileName);
                        
                        foreach ($files as $f => $file) {
                            $newFileName = \Yii::$app->security
                            ->generateRandomString().'.'.$file->extension;
                            if ($file->saveAs($smallPath . '/' . $newFileName, false) && $file->saveAs($largePath . '/' . $newFileName)) {
                                $imgModel = new \common\models\Images;

backend/views/classified/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\ClassifiedCategories;
use common\models\LocationsCounties;
use common\models\LocationsTowns;
use kartik\select2\Select2;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model common\models\ClassifiedListings */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="classified-listings-form">

    <?php $form = ActiveForm::begin(); ?>

    <?=
            $form->field($model, 'ad_type')
            ->dropDownList([
                'private' => 'Private',
                'business' => 'Business',
                    ], [
                'prompt' => 'Ad Type',
                'onchange' => '
                    $.post("' . Yii::$app->urlManager->createUrl('classified/users-list?user_type=') . '"+$(this).val(),function(data){
                        $("select#classifiedlistings-user_id").html(data);
                        });'
            ])
    ?>
    <?php
        $name = "";
        if(isset($model->user_id) && !empty($model->user_id)){
            $user = \common\models\Users::findIdentity($model->user_id);
            $name = $user->contact_name;
        }
        
        
    ?>
    <?=
    $form->field($model, 'user_id')->widget(Select2::classname(), [
        'initValueText' => $name, 
        'size' => Select2::MEDIUM,
        'options' => ['placeholder' => 'Enter Name of User'],
        'pluginOptions' => [
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
            ],
            'ajax' => [
                'url' => Yii::$app->urlManager->createUrl("classified/users-list-ajax"),
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { 
                    var type = $("#classifiedlistings-ad_type").val();
                    return {
                        q:params.term,
                        ad_type:type
                    }; 
                }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(users) { console.log(users); return users.text; }'),
            'templateSelection' => new JsExpression('function (users) { return users.text; }'),
        ],
    ])->label('User');
    ?>

    

    <?=
    $form->field($model, 'county_id')->dropDownList(
            ArrayHelper::map(
                    LocationsCounties::find()->all(), 'id', 'county'), [
        'prompt' => 'Select Country',
        'onchange' => '$.post("/site/lists?id=' . '"+$(this).val(),function(data){
            $("select#classifiedlistings-town_id").html(data);}
        );'
    ])->label('County')
    ?>

    <?= $form->field($model, 'town_id')->dropDownList(ArrayHelper::map(LocationsTowns::find()->all(), 'id', 'town'), ['prompt' => 'Select Town'])->label('Town') ?>

    <?= $form->field($model, 'telephone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true])->label("Mobile *") ?>

    <?= $form->field($model, 'other')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->label("Email *") ?>

    <?= $form->field($model, 'item_status')->dropDownList(['for sale' => 'For sale', 'wanted' => 'Wanted', 'sold' => 'Sold', 'to let' => 'To let', 'available' => 'Available',], ['prompt' => '']) ?>

    <?= $form->field($model, 'duration')->textInput() ?>

    <?= $form->field($model, 'featured')->dropDownList(['no' => 'No', 'yes' => 'Yes',], ['prompt' => '']) ?>

    <?= $form->field($model, 'buy_now_url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true])->label("Title *") ?>

    <?=
    $form->field($model, 'parent_id')->dropDownList(ArrayHelper::map(
                    ClassifiedCategories::find()->getCategories()->all(), 'id', 'category'
            ), [
        'prompt' => 'Parent Category',
        'onchange' => '$.post("' . Yii::$app->urlManager->createUrl('classified-categories/child-cats?id=') . '"+$(this).val(),function(data){
                                                    $("select#classifiedlistings-classified_cat_id").html(data);
                                                    });'
    ])->label('Select Parent Category *');
    ?>

    <?=
    $form->field($model, 'classified_cat_id')->dropDownList(ArrayHelper::map(
                    ClassifiedCategories::find()->all(), 'id', 'category'
            ), [
        'prompt' => 'Select Child Category',
    ])->label('Child Category *');
    ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6])->label("Description *") ?>

    <?= $form->field($model, 'currency')
                                    ->dropDownList([
                                            'EUR' => "€",
                                            'GBP' => "£",
                                            'FREE' => 'FREE',
                                    ])->label('Select currency *')?>

<?= $form->field($model, 'price')->textInput(['maxlength' => true])->label("Price *") ?>

    <div class="form-group">
<?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

backend/views/classified/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ClassifiedSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="classified-listings-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'parent_id') ?>

    <?= $form->field($model, 'classified_cat_id') ?>

    <?= $form->field($model, 'sub_category') ?>

    <?= $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'image_count') ?>

    <?php // echo $form->field($model, 'ad_type') ?>

    <?php // echo $form->field($model, 'title') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'search_options') ?>

    <?php // echo $form->field($model, 'currency') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'search_price') ?>

    <?php // echo $form->field($model, 'price_suffix') ?>

    <?php // echo $form->field($model, 'duration') ?>

    <?php // echo $form->field($model, 'town_id') ?>

    <?php // echo $form->field($model, 'county_id') ?>

    <?php // echo $form->field($model, 'item_status') ?>

    <?php // echo $form->field($model, 'telephone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'mobile') ?>

    <?php // echo $form->field($model, 'other') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'order') ?>

    <?php // echo $form->field($model, 'bump') ?>

    <?php // echo $form->field($model, 'bump_count') ?>

    <?php // echo $form->field($model, 'featured') ?>

    <?php // echo $form->field($model, 'date_sold') ?>

    <?php // echo $form->field($model, 'views') ?>

    <?php // echo $form->field($model, 'start_date') ?>

    <?php // echo $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'make_id') ?>

    <?php // echo $form->field($model, 'auto_make') ?>

    <?php // echo $form->field($model, 'model_id') ?>

    <?php // echo $form->field($model, 'auto_model') ?>

    <?php // echo $form->field($model, 'year') ?>

    <?php // echo $form->field($model, 'fuel') ?>

    <?php // echo $form->field($model, 'body_type') ?>

    <?php // echo $form->field($model, 'colour') ?>

    <?php // echo $form->field($model, 'engine_size') ?>

    <?php // echo $form->field($model, 'version') ?>

    <?php // echo $form->field($model, 'date_added') ?>

    <?php // echo $form->field($model, 'business_plus_url') ?>

    <?php // echo $form->field($model, 'edition_one') ?>

    <?php // echo $form->field($model, 'edition_two') ?>

    <?php // echo $form->field($model, 'edition_three') ?>

    <?php // echo $form->field($model, 'edition_four') ?>

    <?php // echo $form->field($model, 'edition_date') ?>

    <?php // echo $form->field($model, 'buy_now_url') ?>

    <?php // echo $form->field($model, 'transmission') ?>

    <?php // echo $form->field($model, 'co2_emissions') ?>

    <?php // echo $form->field($model, 'nct_date') ?>

    <?php // echo $form->field($model, 'tax_date') ?>

    <?php // echo $form->field($model, 'mileage') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/classified/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\ClassifiedListings */

$this->title = Yii::t('app', 'Create Classified Listings');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Classified Listings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="classified-listings-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/classified/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\models\MyActiveRecord;
use kartik\daterange\DateRangePicker;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ClassifiedSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$title = (isset($_GET['ClassifiedSearch']['ad_type']) && !empty($_GET['ClassifiedSearch']['ad_type'])) ? $_GET['ClassifiedSearch']['ad_type'] : "";



$this->title = ucfirst($title)." ".Yii::t('app', 'Classified Listings');
$this->params['breadcrumbs'][] = Yii::t('app', 'Classified Listings');



?>
<div class="classified-listings-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Classified Listings'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],
            'title',
            [
                'attribute' => 'parent_id',
                'label' => 'Category',
                'value' => 'classifiedCat.category'
            ],
            [
                'attribute'=>'status',
                'filter' =>Html::activeDropDownList($searchModel, 'status', array("active"=>"Active","inactive"=>"InActive"),['class'=>'form-control','prompt' => 'Select Status']),
            ],
//            'bump',
//            'bump_count',
            [
                // the attribute
                'attribute' => 'start_date',
                // format the value
                'value' => function ($model) {
                    return (!empty($model->start_date)) ? MyActiveRecord::convertTimeStampIntoDate($model->start_date) : '';
                },
                // some styling?
                'headerOptions' => [
                    //'class' => 'col-md-2'
                ],
                // here we render the widget
                'filter' => DateRangePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'start_date',
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'timePicker' => true,
                        'timePickerIncrement' => 30,
                        'locale' => [
                            'format' => 'd-m-Y'
                        ]
                    ]
                ])
            ],
            [
                // the attribute
                'attribute' => 'end_date',
                // format the value
                'value' => function ($model) {
                    return (!empty($model->end_date)) ? MyActiveRecord::convertTimeStampIntoDate($model->end_date) : '';
                },
                // some styling?
                'headerOptions' => [
                    //'class' => 'col-md-2'
                ],
                // here we render the widget
                'filter' => DateRangePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'end_date',
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'timePicker' => true,
                        'timePickerIncrement' => 30,
                        'locale' => [
                            'format' => 'd-m-Y'
                        ]
                    ]
                ])
            ],

//            ['class' => 'yii\grid\ActionColumn'],
            ['class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'text-align:center;width: 100px !important;'],
                'template' => '{update} {delete}',
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/classified/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ClassifiedListings */

$this->title = Yii::t('app', 'Update Classified Listings: ' . $model->title, [
    'nameAttribute' => '' . $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Classified Listings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="classified-listings-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>