backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Users;
use backend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\AdminController;
use common\models\LocationsTowns;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'view', 'delete', 'town-lists'],
                'rules' => [
                    // allow authenticated users
                        [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->identity->user_type != \common\models\Users::ROLE_ADMIN) {
                                return $this->redirect('/login');
                            }else if(Yii::$app->user->identity->user_type == \common\models\Users::ROLE_ADMIN){
                                return true;
                            }
                        }
                    ],
                // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryParams = Yii::$app->request->queryParams;
        //Validate user type
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search($queryParams);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->redirect(Yii::$app->request->referrer);
        return $this->render('update', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $user_type = $queryParams = Yii::$app->request->queryParams;
        $model = new Users();

        $model->setScenario($user_type['user_type']);

        if(isset(Yii::$app->request->isPost)) {
            if ($model->load(Yii::$app->request->post())) {

                $password = Yii::$app->security->generateRandomString(6);
                $model->setPassword($password);
                $post = Yii::$app->request->post();
                $model->date_added = time();
                if ($user = $model->save() && $model->sendAccountDetailsEmail($password)) {
                    Yii::$app->session->setFlash('success', 'Record created successfully.');
                    return $this->redirect(Yii::$app->request->referrer);
                } else {
                    Yii::$app->session->setFlash('error', 'Something went wrong.');
                }
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario($model->user_type);

        if (isset(Yii::$app->request->isPost) && $model->load(Yii::$app->request->post())){
            $posts = Yii::$app->request->post();
            $model->load(Yii::$app->request->post());
            if ($model->id == Yii::$app->user->identity->id ) {
                if ($model->change_password == 1){
                    $model->setPassword($posts['Users']['password']);
                }
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Record Updated successfully.');
                return $this->redirect(Yii::$app->request->referrer);
            } else {
                Yii::$app->session->setFlash('success', 'Record Not Updated.');
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('success', 'Your account has been Updated successfully.');

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionTownLists($id) {
        $posts = LocationsTowns::find()
            ->where(['county_id' => $id])
            ->all();
        if (!empty($posts)) {
            echo '<option value="0"> Select Town </option>';
            foreach ($posts as $post) {
                echo '<option value="'.$post->id.'">'.$post->town.'</option>';
            }
        }
        else{
            echo '<option value="0"> - </option>';
        }
    }
}

frontend/controllers/UsersController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use \common\models\WatchlistLookup;
use frontend\models\ClassifiedSearch;
use common\models\Users;

/**
 * Site controller
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    Yii::$app->session->setFlash('error', 'Please login to continue');
                    return $this->redirect('/login');
                },
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['signup', 'business-details', 'business-json','business-directory','request-password-reset'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['dashboard', 'my-ads', 'buy-credit', 'business-details', 'business-json','business-directory','edit-profile', 'remove-watchlist','my-watchlist','watch-list'],
                        'roles' => ['@'],
                    ],
                // everything else is denied
                ],
            ],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    
    public function actionDashboard()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        return $this->render('dashboard');
    }

    
    public function actionMyAds()
    {
        $id = Yii::$app->user->identity->id;
        $searchModel = new ClassifiedSearch();
        $dataProvider = $searchModel->searchByUser($id);
        
        return $this->render('my-ads',[
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays Buy Credit page.
     *
     * @return mixed
     */
    public function actionBuyCredit()
    {
        return $this->render('buy-credit');
    }

    /**
     * Signs users up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($users = $model->signup()) {
                if (Yii::$app->getUsers()->login($users)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }
    
    /**
     * Edit Profile
     *
     * @return mixed
     */
    public function actionEditProfile()
    {
        
        $model = \common\models\Users::findOne($userId = Yii::$app->user->identity->id);
        $model->setScenario($model->user_type);
        if ($model->load(Yii::$app->request->post())) {
            if ($users = $model->save(false)) {
                Yii::$app->session->setFlash('success', 'Profile Updated Successfully');
            }
        }

        return $this->render("edit-profile", [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    
    public function actionWatchList($id){
        
        if(yii::$app->user->isGuest){
            return $this->redirect(Yii::$app->request->referrer);
        }
        $userId = Yii::$app->user->identity->id;
        $ifExist = WatchlistLookup::find()
                                    ->where(['user_id' => $userId,'listing_id' => $id])
                                    ->one();
        
        
        if(!empty($ifExist) && count($ifExist) > 0){
            Yii::$app->session->setFlash('error', 'Alreay Added in Watchlist');
            if(Yii::$app->request->isAjax){
                $response = array('status' => 'error','msg' => 'Alreay Added in Watchlist');
                return json_encode($response);exit;
            }
            return $this->redirect(Yii::$app->request->referrer);
        }else{
            $model = new WatchlistLookup();
            
            $model->user_id = $userId;
            $model->listing_id = $id;
            if($model->save(false)){
                Yii::$app->session->setFlash('success', 'Added to watchlist');
                if(Yii::$app->request->isAjax){
                    $response = array('status' => 'success');
                    return json_encode($response);exit;
                }
                return $this->redirect(Yii::$app->request->referrer);
            }
        }
    }
    
    public function actionMyWatchlist(){
        
        $userId = Yii::$app->user->identity->id;
        $watchlist = WatchlistLookup::find()
                                    ->where(['user_id' => $userId])
                                    ->all();
        
        return $this->render('watch-list', [
            'model' => $watchlist,
        ]);
        
    }
    
    public function actionRemoveWatchlist($id){
        
        if(yii::$app->user->isGuest){
            return $this->redirect(Yii::$app->request->referrer);
        }
        $userId = Yii::$app->user->identity->id;
        $ifExist = WatchlistLookup::find()
                                    ->where(['user_id' => $userId,'listing_id' => $id])
                                    ->one();
                                    
        if($ifExist->delete()){
            Yii::$app->session->setFlash('error', 'Removed from Watchlist');
            return $this->redirect(Yii::$app->request->referrer);
        }   
    }
    
    public function actionBusinessDirectory(){
        
//        $searchModel = new \frontend\models\UsersSearch();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $countries = \common\models\LocationsCounties::find()->all();
        
        $countyTowns = [];
        foreach ($countries as $c => $country){
            $countyTowns[$country->slug."~".$country->id] = $country->county;
            $towns = \common\models\LocationsTowns::find()->where(['county_id' => $country->id])->all();
            if(!empty($towns) && count($towns) > 0){
                foreach ($towns as $t => $town){
                    $countyTowns[$town->slug."~".$town->id] = $country->county." - ".$town->town;
                }
            }
        }
//        echo "<pre>";
//        print_r($countyTowns);exit;
        return $this->render('business-list', [
//            'searchModel' => $searchModel,
//            'dataProvider' => $dataProvider,
            'countyTowns' => $countyTowns
        ]);
        
    }
    
    public function actionCheckout(){
        // Setup order information array with all items
        $params = [
            'method'=>'paypal',
            'intent'=>'sale',
            'order'=>[
                'description'=>'Payment description',
                'subtotal'=>44,
                'shippingCost'=>0,
                'total'=>44,
                'currency'=>'USD',
                'items'=>[
                    [
                        'name'=>'Item one',
                        'price'=>10,

frontend/views/users/_item.php
<?php

/** @var Item $model */

use frontend\components\users\UsersAdsListingWidget;

echo UsersAdsListingWidget::widget(['model' => $model]);

frontend/views/users/business-details.php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use common\models\Images;
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\WatchlistLookup;
use common\models\ClassifiedListings;
use ymaker\social\share\widgets\SocialShare;

$this->title = $dataProvider->models[0]->company_name;
//echo "<pre>";
//print_r($dataProvider->models);
?>

<div class="content-wrapper directory-detais-wrap mt-5">
    <div class="container">
        <div class="directory-details mb-5">
            <h2 class="sec-heading mb-4"><?= $dataProvider->models[0]->company_name ?></h2>
            <div class="direction-form">
                <div class="form">
                    <form id="direction-form" action="#" onsubmit="setDirections(this.location.value); return false">
                        <div class="row no-gutters">
                            <div class="col-lg-10 col-md-9 col-sm-8 mb-2">
                                <div class="form-group required mb-0 mr-0 mr-sm-2">
                                    <input type="text" class="form-control" name="location" placeholder="Enter Your Location">
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-4 mb-2">
                                <button type="submit" class="btn btn-lg btn-block btn-grey" name="direction-button">Get Direction</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="directory-info-wrap">
                <div class="row">
                    <div class="col-md-5 col-lg-4 mb-3 mb-md-0">
                        <div class="directory-info border">
                            <div class="contact-name border-bottom">
                                <h4 class="sub-sec-heading">Contact</h4>
                                <p class="sec-content"><?= $dataProvider->models[0]->company_name ?></p>
                            </div>
                            <div class="address border-bottom">
                                <h4 class="sub-sec-heading">Address</h4>
                                <p class="sec-content"><?= $dataProvider->models[0]->address_one ?></p>
                                <p class="sec-content"><?= (isset($dataProvider->models[0]->address_two) && !empty($dataProvider->models[0]->address_two)) ? $dataProvider->models[0]->address_two : "";  ?></p>
                            </div>
                            <div class="phone border-bottom">
                                <h4 class="sub-sec-heading">Tel</h4>
                                <p class="sec-content"><?= $dataProvider->models[0]->telephone ?></p>
                            </div>
                            <div class="web-info border-bottom">
                                <h4 class="sub-sec-heading">Website</h4>
                                <p class="sec-content">
                                    <?php $website = (isset($dataProvider->models[0]->website) && !empty($dataProvider->models[0]->website)) ? $dataProvider->models[0]->website : "";  ?>
                                    <a href="<?= $website ?>"><?= $website ?></a>
                                </p>
                            </div>
                            <div class="email-info">
                                <h4 class="sub-sec-heading">Email</h4>
                                <p class="sec-content">
                                    <a href="mailto:<?= $dataProvider->models[0]->email ?>"><?= $dataProvider->models[0]->email ?></a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class=" col-md-7 col-lg-8 location-map">
                        <div id="map_canvas_small" style="width:100%;height:400px;"></div>
                        <div id="directions-panel"></div>
                        <p class="location-cords">
                            <span class="mr-3">Lat:<span id="user-lat"><?= $dataProvider->models[0]->user_lat ?></span>
                            <span>Long:<span id="user-long"><?= $dataProvider->models[0]->user_long ?></span></span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="page-action">
                <a class="mr-2" href="javascript:window.print()">Print</a> | <a class="ml-2" href="#">Share</a>
                <?= SocialShare::widget([
                    'configurator'  => 'socialShare',
                    'url'           => Url::to('/users/business-details?UsersSearch[id]='.Html::encode($dataProvider->models[0]->id), true),
                    'title'         => Html::encode($dataProvider->models[0]->company_name),
                    'description'   => Html::encode($dataProvider->models[0]->description),
                    'containerOptions' => ['tag' => 'div', 'class' => 'social-share mb-4'],
                    'linkContainerOptions' => ['tag' => false],
                ]); ?>
            </div>
        </div>
        <?php if(isset($ads) && count($ads) > 0 ): ?>
        <div class="user-ads mb-4">
            <h3 class="sec-heading">User Ads</h3>
            <div class="ads-listing">
                <div class="row no-gutters">
                    <?php
                        foreach ($ads as $r => $relatedAd):

                    ?>
                    <div class="col-md-3 col-sm-4 col-xs-6 ads-grid">
                        <a class="ads-grid-content border" href="<?= Url::to('/classified/view?ClassifiedSearch[id]='.Html::encode($relatedAd->id)) ?>">
                            <?php
                            $images = Images::find()->select('image_name')->getImages(ClassifiedListings::tableName(),$relatedAd->id)->one();
                            if(!empty($images)){
                                $imagePath = \Yii::getAlias('@webroot').'/uploads/small/'.$images->image_name;
                            }else{
                                $imagePath = "";
                            }

                            ?>
                            <?php if (file_exists($imagePath)) { ?>
                                <?= Html::img('/uploads/small/'.$images->image_name, ['alt'=> $relatedAd->title, 'title'=>$relatedAd->title, 'class'=>'ads_img' ]); ?>
                            <?php } else { ?>
                                <?= Html::img('/images/no_images_thumb.jpg', ['alt'=> $relatedAd->title, 'title'=>$relatedAd->title, 'class'=>'ads_img' ]) ?>
                            <?php } ?>
                            <div class="meta-info border-bottom">
                                <span class="price"><?= Yii::$app->params[$relatedAd->currency] ?></sup><?= $relatedAd->price ?></span>
                                <span class="watch ajaxSave float-right" data-url="<?= Url::toRoute(['/users/watch-list']) ?>" data-id="<?= $relatedAd->id ?>">
                                    <i class="far fa-heart fa-fw fa-lg"></i>
                                </span>
                            </div>
                            <h4 class="ad-title"><?= $relatedAd->title ?></h4>
                            <p class="location"><?= $relatedAd->town->town."," .$relatedAd->county->county ?></p>
                        </a>
                    </div>
                    <?php
                        endforeach;
                    ?>
                </div>
            </div>
            <?php if(count($ads) > 8): ?>
            <div class="text-center mt-4 mb-5">
                <a href="<?= Url::to('/classified/search?ClassifiedSearch[user_id]='.$dataProvider->models[0]->id) ?>" class="btn btn-default btn-lg">See All</a>
            </div>
            <?php endif; ?>
        </div>
        <?php  endif; ?>
    </div>
</div>

frontend/views/users/business-user-list.php
<?php

/** @var Item $model */

use frontend\components\users\BusinessUsersListingWidget;

echo BusinessUsersListingWidget::widget(['model' => $model,'index' => $index]);

frontend/views/users/buy-credit.php
<div class="buy-credit">
    <div class="container">
        <div class="credit-wrapper mt-4">
            <h3 class="page-title mb-3">Your Account Balance is &#8364;0.00</h3>
            <p class="page-title-desc">You require a minimum of €3 in your account to purchase this online issue.</p>
            <p class="page-title-desc">Please top up your account with a minimum of €3.</p>
            <div class="credit-method mt-4">
                <h3>Buy Credit</h3>
                <div class="form buy-credit-form"> 
                    <form action="#" method="post" accept-charset="utf-8" class="form">
                        <div class="form-group required">
                            <div class="cstm-radio" aria-required="true">
                                <label class="radio-inline d-block">
                                    <input type="radio" name="BuyCredit[method]" value="paypal" checked> 
                                    <img src="/images/paypal_logo.png" alt="">
                                </label>
                                <label class="radio-inline d-block">
                                    <input type="radio" name="BuyCredit[method]" value="visa"> 
                                    <img src="/images/visa_logo.png" alt="">
                                </label>
                                <label class="radio-inline d-block">
                                    <input type="radio" name="BuyCredit[method]" value="mastercard"> 
                                    <img src="/images/mastercard_logo.png" alt="">
                                </label>
                            </div>
                        </div>  
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/users/dashboard.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use yii\helpers\Html;



$this->title = Yii::t('app', 'Dashboard');

?>
<div class="dashboard">
    <div class="container">
        <div class="dash-content-wrapper mt-5">
            <h3 class="page-title mb-5">What would you like to do today?</h3>
            <div class="dash-content mt-4">
                <div class="row">
                    <div class="col-md-6 col-12">
                        <div class="row dash-menus mb-md-0 mb-4">
                            <div class="col-md-6 col-sm-6 col-6 mx-auto pr-2">
                                <div class="my-ads menus-item">
                                    <a href="<?= yii\helpers\Url::to('my-ads'); ?>">
                                        <div class="menus-img">
                                            <?= Html::img('/images/myads.png', ['alt'=>'My Ads', 'class'=>'img-fluid']); ?>
                                        </div>
                                        <h4 class="action-head">My Ads</h4>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-6 mx-auto pl-2">
                                <div class="whatchlist menus-item">
                                    <a href="<?= yii\helpers\Url::to('my-watchlist'); ?>"> 
                                        <div class="menus-img">
                                            <?= Html::img('/images/watchlist.png', ['alt'=>'My Ads', 'class'=>'img-fluid']); ?>
                                        </div>
                                        <h4 class="action-head">Watchlist</h4>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-6 mx-auto pr-2">
                                <div class="credit menus-item">
                                    <a href="<?= yii\helpers\Url::to('/users/buy-credit'); ?>">
                                        <div class="menus-img">
                                            <?= Html::img('/images/credit-card.png', ['alt'=>'My Ads', 'class'=>'img-fluid']); ?>
                                        </div>
                                        <h4 class="action-head">Credit</h4>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-6 mx-auto pl-2">
                                <div class="edit_account menus-item">
                                    <a href="<?= yii\helpers\Url::to('edit-profile'); ?>">
                                        <div class="menus-img">
                                            <?= Html::img('/images/edit_account.png', ['alt'=>'My Ads', 'class'=>'img-fluid']); ?>
                                        </div>
                                        <h4 class="action-head">Edit Account</h4>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-12">
                        <div class="start_selling">
                            <h4>Place a free Advert</h4>
                            <p>Four months online, ten large photos and listing in local printed edition.</p>
                            <a href="/create" class="btn btn-default btn-lg mt-3"><strong>START SELLING</strong></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>